In [2]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

In [3]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame
import Bio
from Bio import SeqIO,AlignIO
from sklearn.feature_extraction.text import CountVectorizer

In [8]:
def get_kmer_table(genes,gene_len,k_min,k_max):
    
    count_vect = CountVectorizer(analyzer='char',ngram_range=(k_min,k_max))
    X = count_vect.fit_transform(genes)
    chars = count_vect.get_feature_names()
    chars
    kmers = X.toarray()
    kmer_freq = []
    for i in range(len(genes)):
        kmer_freq.append(kmers[i]/gene_len[i])
    input = pd.DataFrame(kmer_freq,columns=chars)
    return input

def get_ids(filename):
    ids = []
    for record in SeqIO.parse(filename, "fasta"):
        ids.append(record.id)

def get_gene_sequences(filename):
    genes = []
    for record in SeqIO.parse(filename, "fasta"):
        genes.append(str(record.seq))
    return genes

# genes: a list of gene sequences, which can directly be generated from get_gene_sequences().
def get_gene_len(genes):
    gene_len = []
    
    for i in range(len(genes)):
        gene_len.append(len(genes[i]))
    return gene_len

In [9]:
genes_0 = get_gene_sequences("label0.fasta")
genes_1 = get_gene_sequences("label1.fasta")
gene_len_0 = get_gene_len(genes_0)
gene_len_1 = get_gene_len(genes_1)
all_genes = genes_0 + genes_1
all_gene_len = gene_len_0 + gene_len_1
kmer_table = get_kmer_table(all_genes,all_gene_len,5,6)
kmer_table

aaaaa    aaaaaa    aaaaac    aaaaag    aaaaat     aaaac    aaaaca  \
0    0.002347  0.000204  0.000918  0.000612  0.000612  0.001735  0.000918   
1    0.000000  0.000000  0.000000  0.000000  0.000000  0.000243  0.000243   
2    0.001649  0.001335  0.000236  0.000000  0.000000  0.001021  0.000157   
3    0.000748  0.000000  0.000499  0.000000  0.000249  0.001746  0.000499   
4    0.001517  0.000433  0.000217  0.000433  0.000433  0.001733  0.000000   
..        ...       ...       ...       ...       ...       ...       ...   
352  0.002400  0.001783  0.000206  0.000137  0.000206  0.001029  0.000206   
353  0.001186  0.000000  0.000395  0.000395  0.000395  0.001976  0.001186   
354  0.001084  0.000000  0.000465  0.000155  0.000465  0.001704  0.000619   
355  0.001509  0.000335  0.000503  0.000503  0.000168  0.001509  0.000838   
356  0.002500  0.000600  0.000600  0.000300  0.001000  0.002400  0.000900   

       aaaacc    aaaacg    aaaact  ...  ygcwa  ygcwag  ygtac  ygtacg  ysccg  \
0    0.000102  0.000102  0.000612  ...    0.0     0.0    0.0     0.0    0.0   
1    0.000000  0.000000  0.000000  ...    0.0     0.0    0.0     0.0    0.0   
2    0.000550  0.000157  0.000157  ...    0.0     0.0    0.0     0.0    0.0   
3    0.000249  0.000249  0.000748  ...    0.0     0.0    0.0     0.0    0.0   
4    0.000650  0.000433  0.000650  ...    0.0     0.0    0.0     0.0    0.0   
..        ...       ...       ...  ...    ...     ...    ...     ...    ...   
352  0.000411  0.000206  0.000206  ...    0.0     0.0    0.0     0.0    0.0   
353  0.000000  0.000000  0.000791  ...    0.0     0.0    0.0     0.0    0.0   
354  0.000465  0.000155  0.000465  ...    0.0     0.0    0.0     0.0    0.0   
355  0.000503  0.000000  0.000168  ...    0.0     0.0    0.0     0.0    0.0   
356  0.000200  0.000000  0.001300  ...    0.0     0.0    0.0     0.0    0.0   

     ysccgg  ytcag  ytcagt  yttac  yttacg  
0       0.0    0.0     0.0    0.0     0.0  
1       0.0    0.0     0.0    0.0     0.0  
2       0.0    0.0     0.0    0.0     0.0  
3       0.0    0.0     0.0    0.0     0.0  
4       0.0    0.0     0.0    0.0     0.0  
..      ...    ...     ...    ...     ...  
352     0.0    0.0     0.0    0.0     0.0  
353     0.0    0.0     0.0    0.0     0.0  
354     0.0    0.0     0.0    0.0     0.0  
355     0.0    0.0     0.0    0.0     0.0  
356     0.0    0.0     0.0    0.0     0.0  

[357 rows x 5529 columns]

In [10]:
from sklearn.mixture import GaussianMixture as GMM
gmm = GMM(n_components=2).fit(kmer_table)
labels = gmm.predict(kmer_table)

In [11]:
# 5-6 
labels

array([1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,

In [12]:
kmer_table2 = get_kmer_table(all_genes,all_gene_len,7,7)
kmer_table2

aaaaaaa  aaaaaac   aaaaaag   aaaaaat   aaaaaca   aaaaacc   aaaaacg  \
0    0.000000   0.0000  0.000102  0.000102  0.000714  0.000000  0.000000   
1    0.000000   0.0000  0.000000  0.000000  0.000000  0.000000  0.000000   
2    0.001256   0.0000  0.000000  0.000000  0.000000  0.000157  0.000079   
3    0.000000   0.0000  0.000000  0.000000  0.000000  0.000000  0.000000   
4    0.000000   0.0000  0.000000  0.000433  0.000000  0.000000  0.000217   
..        ...      ...       ...       ...       ...       ...       ...   
352  0.001715   0.0000  0.000000  0.000000  0.000000  0.000137  0.000069   
353  0.000000   0.0000  0.000000  0.000000  0.000395  0.000000  0.000000   
354  0.000000   0.0000  0.000000  0.000000  0.000155  0.000155  0.000000   
355  0.000000   0.0000  0.000168  0.000168  0.000168  0.000335  0.000000   
356  0.000100   0.0001  0.000000  0.000400  0.000400  0.000000  0.000000   

      aaaaact   aaaaaga   aaaaagc  ...  yatgaag  ycgcgtg  ycgtcac  ygacgtg  \
0    0.000204  0.000102  0.000000  ...      0.0      0.0      0.0      0.0   
1    0.000000  0.000000  0.000000  ...      0.0      0.0      0.0      0.0   
2    0.000000  0.000000  0.000000  ...      0.0      0.0      0.0      0.0   
3    0.000499  0.000000  0.000000  ...      0.0      0.0      0.0      0.0   
4    0.000000  0.000433  0.000000  ...      0.0      0.0      0.0      0.0   
..        ...       ...       ...  ...      ...      ...      ...      ...   
352  0.000000  0.000000  0.000000  ...      0.0      0.0      0.0      0.0   
353  0.000000  0.000395  0.000000  ...      0.0      0.0      0.0      0.0   
354  0.000155  0.000000  0.000155  ...      0.0      0.0      0.0      0.0   
355  0.000000  0.000335  0.000168  ...      0.0      0.0      0.0      0.0   
356  0.000200  0.000300  0.000000  ...      0.0      0.0      0.0      0.0   

     ygatggt  ygcwagr  ygtacgc  ysccggc  ytcagtc  yttacgt  
0        0.0      0.0      0.0      0.0      0.0      0.0  
1        0.0      0.0      0.0      0.0      0.0      0.0  
2        0.0      0.0      0.0      0.0      0.0      0.0  
3        0.0      0.0      0.0      0.0      0.0      0.0  
4        0.0      0.0      0.0      0.0      0.0      0.0  
..       ...      ...      ...      ...      ...      ...  
352      0.0      0.0      0.0      0.0      0.0      0.0  
353      0.0      0.0      0.0      0.0      0.0      0.0  
354      0.0      0.0      0.0      0.0      0.0      0.0  
355      0.0      0.0      0.0      0.0      0.0      0.0  
356      0.0      0.0      0.0      0.0      0.0      0.0  

[357 rows x 16641 columns]

In [13]:
gmm2 = GMM(n_components=2).fit(kmer_table2)
labels2 = gmm2.predict(kmer_table2)
labels2

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [15]:
#5-mer

kmer_table3 = get_kmer_table(all_genes,all_gene_len,5,5)
kmer_table3

gmm3 = GMM(n_components=2,covariance_type="full").fit(kmer_table3)
labels3 = gmm3.predict(kmer_table3)
labels3

array([0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,

In [16]:
gmm3 = GMM(n_components=2,covariance_type="tied").fit(kmer_table)
labels3 = gmm3.predict(kmer_table)
labels3

array([1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,

In [19]:
# 6

kmer_table4 = get_kmer_table(all_genes,all_gene_len,6,6)
kmer_table4

gmm4 = GMM(n_components=2,covariance_type="full").fit(kmer_table4)
labels4 = gmm4.predict(kmer_table4)
labels4

array([0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,