In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

In [2]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame
import Bio
from Bio import SeqIO,AlignIO
from sklearn.feature_extraction.text import CountVectorizer

In [3]:
def get_kmer_table(genes,gene_len,k_min,k_max):
    
    count_vect = CountVectorizer(analyzer='char',ngram_range=(k_min,k_max))
    X = count_vect.fit_transform(genes)
    chars = count_vect.get_feature_names()
    chars
    kmers = X.toarray()
    kmer_freq = []
    for i in range(len(genes)):
        kmer_freq.append(kmers[i]/gene_len[i])
    input = pd.DataFrame(kmer_freq,columns=chars)
    return input

def get_ids(filename):
    ids = []
    for record in SeqIO.parse(filename, "fasta"):
        ids.append(record.id)

def get_gene_sequences(filename):
    genes = []
    for record in SeqIO.parse(filename, "fasta"):
        genes.append(str(record.seq))
    return genes

# genes: a list of gene sequences, which can directly be generated from get_gene_sequences().
def get_gene_len(genes):
    gene_len = []
    
    for i in range(len(genes)):
        gene_len.append(len(genes[i]))
    return gene_len

In [4]:
genes_0 = get_gene_sequences("label0.fasta")
genes_1 = get_gene_sequences("label1.fasta")
gene_len_0 = get_gene_len(genes_0)
gene_len_1 = get_gene_len(genes_1)
all_genes = genes_0 + genes_1
all_gene_len = gene_len_0 + gene_len_1
kmer_table = get_kmer_table(all_genes,all_gene_len,5,6)
kmer_table

aaaaa    aaaaaa    aaaaac    aaaaag    aaaaat     aaaac    aaaaca  \
0    0.002347  0.000204  0.000918  0.000612  0.000612  0.001735  0.000918   
1    0.000000  0.000000  0.000000  0.000000  0.000000  0.000243  0.000243   
2    0.001649  0.001335  0.000236  0.000000  0.000000  0.001021  0.000157   
3    0.000748  0.000000  0.000499  0.000000  0.000249  0.001746  0.000499   
4    0.001517  0.000433  0.000217  0.000433  0.000433  0.001733  0.000000   
..        ...       ...       ...       ...       ...       ...       ...   
352  0.002400  0.001783  0.000206  0.000137  0.000206  0.001029  0.000206   
353  0.001186  0.000000  0.000395  0.000395  0.000395  0.001976  0.001186   
354  0.001084  0.000000  0.000465  0.000155  0.000465  0.001704  0.000619   
355  0.001509  0.000335  0.000503  0.000503  0.000168  0.001509  0.000838   
356  0.002500  0.000600  0.000600  0.000300  0.001000  0.002400  0.000900   

       aaaacc    aaaacg    aaaact  ...  ygcwa  ygcwag  ygtac  ygtacg  ysccg  \
0    0.000102  0.000102  0.000612  ...    0.0     0.0    0.0     0.0    0.0   
1    0.000000  0.000000  0.000000  ...    0.0     0.0    0.0     0.0    0.0   
2    0.000550  0.000157  0.000157  ...    0.0     0.0    0.0     0.0    0.0   
3    0.000249  0.000249  0.000748  ...    0.0     0.0    0.0     0.0    0.0   
4    0.000650  0.000433  0.000650  ...    0.0     0.0    0.0     0.0    0.0   
..        ...       ...       ...  ...    ...     ...    ...     ...    ...   
352  0.000411  0.000206  0.000206  ...    0.0     0.0    0.0     0.0    0.0   
353  0.000000  0.000000  0.000791  ...    0.0     0.0    0.0     0.0    0.0   
354  0.000465  0.000155  0.000465  ...    0.0     0.0    0.0     0.0    0.0   
355  0.000503  0.000000  0.000168  ...    0.0     0.0    0.0     0.0    0.0   
356  0.000200  0.000000  0.001300  ...    0.0     0.0    0.0     0.0    0.0   

     ysccgg  ytcag  ytcagt  yttac  yttacg  
0       0.0    0.0     0.0    0.0     0.0  
1       0.0    0.0     0.0    0.0     0.0  
2       0.0    0.0     0.0    0.0     0.0  
3       0.0    0.0     0.0    0.0     0.0  
4       0.0    0.0     0.0    0.0     0.0  
..      ...    ...     ...    ...     ...  
352     0.0    0.0     0.0    0.0     0.0  
353     0.0    0.0     0.0    0.0     0.0  
354     0.0    0.0     0.0    0.0     0.0  
355     0.0    0.0     0.0    0.0     0.0  
356     0.0    0.0     0.0    0.0     0.0  

[357 rows x 5529 columns]

In [5]:
from sklearn.mixture import GaussianMixture as GMM
gmm = GMM(n_components=2).fit(kmer_table)
labels = gmm.predict(kmer_table)

In [12]:
# 5-6 
labels_5_6 = labels
labels_5_6
last7_5_6 = labels_5_6[350:357]
last7_5_6

array([1, 1, 1, 1, 0, 0, 1])

In [13]:
kmer_table2 = get_kmer_table(all_genes,all_gene_len,5,5)
kmer_table2

aaaaa     aaaac     aaaag     aaaat     aaaca     aaacc     aaacg  \
0    0.002347  0.001735  0.001735  0.002143  0.001531  0.000918  0.000918   
1    0.000000  0.000243  0.000000  0.000243  0.000243  0.000243  0.000243   
2    0.001649  0.001021  0.000707  0.000785  0.000628  0.001492  0.001178   
3    0.000748  0.001746  0.000748  0.001746  0.001247  0.000499  0.000998   
4    0.001517  0.001733  0.002384  0.001517  0.001083  0.001300  0.001300   
..        ...       ...       ...       ...       ...       ...       ...   
352  0.002400  0.001029  0.000892  0.000960  0.001372  0.001234  0.000754   
353  0.001186  0.001976  0.001186  0.001186  0.001581  0.001186  0.000395   
354  0.001084  0.001704  0.000929  0.001394  0.001704  0.001084  0.000619   
355  0.001509  0.001509  0.000671  0.001006  0.002012  0.001509  0.000503   
356  0.002500  0.002400  0.001200  0.003099  0.002000  0.001300  0.001000   

        aaact     aaaga     aaagc  ...  yatga  ycgcg  ycgtc  ygacg  ygatg  \
0    0.002041  0.001837  0.001123  ...    0.0    0.0    0.0    0.0    0.0   
1    0.000973  0.000486  0.000486  ...    0.0    0.0    0.0    0.0    0.0   
2    0.001178  0.001099  0.001335  ...    0.0    0.0    0.0    0.0    0.0   
3    0.002245  0.001497  0.001247  ...    0.0    0.0    0.0    0.0    0.0   
4    0.002600  0.002600  0.000650  ...    0.0    0.0    0.0    0.0    0.0   
..        ...       ...       ...  ...    ...    ...    ...    ...    ...   
352  0.000960  0.000960  0.001509  ...    0.0    0.0    0.0    0.0    0.0   
353  0.001581  0.002372  0.001581  ...    0.0    0.0    0.0    0.0    0.0   
354  0.000929  0.000929  0.002323  ...    0.0    0.0    0.0    0.0    0.0   
355  0.001174  0.001676  0.001174  ...    0.0    0.0    0.0    0.0    0.0   
356  0.002500  0.002799  0.000300  ...    0.0    0.0    0.0    0.0    0.0   

     ygcwa  ygtac  ysccg  ytcag  yttac  
0      0.0    0.0    0.0    0.0    0.0  
1      0.0    0.0    0.0    0.0    0.0  
2      0.0    0.0    0.0    0.0    0.0  
3      0.0    0.0    0.0    0.0    0.0  
4      0.0    0.0    0.0    0.0    0.0  
..     ...    ...    ...    ...    ...  
352    0.0    0.0    0.0    0.0    0.0  
353    0.0    0.0    0.0    0.0    0.0  
354    0.0    0.0    0.0    0.0    0.0  
355    0.0    0.0    0.0    0.0    0.0  
356    0.0    0.0    0.0    0.0    0.0  

[357 rows x 1211 columns]

In [14]:
gmm2 = GMM(n_components=2).fit(kmer_table2)
labels_5 = gmm2.predict(kmer_table2)
labels_5

array([1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,

In [15]:
last7_5 = labels_5[350:357]
last7_5

array([1, 1, 1, 1, 0, 0, 1])

In [22]:
#4-mer

kmer_table3 = get_kmer_table(all_genes,all_gene_len,4,4)
kmer_table3

gmm3 = GMM(n_components=2,covariance_type="full").fit(kmer_table3)
labels3 = gmm3.predict(kmer_table3)
labels3

array([1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,

In [23]:
last7_4 = labels3[350:357]

In [24]:
#4-5-mer

kmer_table3 = get_kmer_table(all_genes,all_gene_len,4,5)
kmer_table3

gmm3 = GMM(n_components=2,covariance_type="full").fit(kmer_table3)
labels3 = gmm3.predict(kmer_table3)
labels3

array([0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,

In [25]:
last7_4_5 = labels3[350:357]

In [26]:
# 6

kmer_table4 = get_kmer_table(all_genes,all_gene_len,6,6)
kmer_table4

gmm4 = GMM(n_components=2,covariance_type="full").fit(kmer_table4)
labels4 = gmm4.predict(kmer_table4)
labels4

array([0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,

In [27]:
last7_6 = labels4[350:357]

In [30]:
kmer_table = get_kmer_table(all_genes,all_gene_len,5,5)
kmer_table

gmm = GMM(n_components=3,covariance_type="full").fit(kmer_table)
labels = gmm.predict(kmer_table)
labels

array([0, 1, 0, 0, 0, 2, 1, 1, 1, 0, 1, 0, 0, 1, 2, 2, 1, 1, 2, 2, 2, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 2, 1, 1, 1, 0, 0, 2, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 1, 2,
       0, 0, 2, 0, 2, 0, 0, 0, 0, 2, 1, 1, 1, 1, 1, 1, 2, 2, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 2, 2, 0, 1, 1, 1, 1, 1, 1, 2, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 0, 1, 0, 2, 2, 2, 2, 0, 1,
       1, 0, 0, 0, 2, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 2, 2, 1, 2, 0, 2, 0,
       0, 2, 2, 2, 2, 2, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 2, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2,
       1, 0, 1, 0, 0, 0, 2, 0, 2, 2, 0, 1, 1, 1, 0, 1, 1, 2, 0, 0, 0, 2,
       0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 0, 1, 1, 1, 1, 2, 0,
       1, 0, 2, 2, 2, 0, 1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,

In [31]:
last7_5_3cluster = labels[350:357]

In [32]:
gmm5 = GMM(n_components=4).fit(kmer_table)
labels5 = gmm5.predict(kmer_table)
labels5

array([0, 2, 0, 0, 1, 3, 2, 2, 0, 0, 2, 1, 1, 2, 3, 3, 2, 2, 3, 3, 3, 0,
       0, 2, 0, 1, 0, 2, 2, 1, 1, 1, 1, 3, 2, 2, 0, 0, 0, 3, 2, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 3, 2, 1, 1, 1, 1, 1, 2, 0,
       0, 0, 3, 0, 3, 0, 0, 0, 0, 3, 2, 2, 2, 2, 2, 2, 3, 3, 0, 0, 0, 2,
       2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       2, 2, 2, 2, 1, 2, 2, 2, 2, 3, 3, 0, 2, 2, 2, 2, 2, 2, 3, 0, 2, 0,
       0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 1, 2, 0, 3, 3, 3, 3, 0, 2,
       2, 1, 0, 0, 3, 2, 0, 1, 2, 2, 1, 1, 1, 1, 1, 3, 3, 2, 3, 0, 0, 0,
       0, 3, 3, 3, 3, 3, 2, 2, 1, 1, 1, 0, 1, 0, 2, 2, 0, 3, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 3, 3, 3, 3, 3, 0, 0, 3, 3, 3, 3, 3,
       0, 0, 2, 0, 0, 0, 3, 1, 3, 3, 0, 0, 0, 0, 2, 2, 2, 3, 1, 1, 0, 3,
       1, 3, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 3, 2, 0, 2, 2, 2, 2, 3, 1,
       0, 0, 3, 0, 3, 0, 2, 0, 3, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1,

In [33]:
last7_5_4cluster = labels5[350:357]

In [34]:
df = pd.DataFrame(data=[last7_4,last7_4_5,last7_5,last7_5_6,last7_6,last7_5_3cluster,last7_5_4cluster], index=['4 kmer','4 to 5 kmer','5 kmer','5 to 6 kmers','6 kmer','5 kmer with 3 clusters','5 kmer with 4 clusters'], columns=['No.1','No.2','No.3','No.4','No.5','No.6','No.7'])
df

No.1  No.2  No.3  No.4  No.5  No.6  No.7
4 kmer                     1     1     0     1     0     0     1
4 to 5 kmer                0     0     1     0     1     1     0
5 kmer                     1     1     1     1     0     0     1
5 to 6 kmers               1     1     1     1     0     0     1
6 kmer                     0     0     0     0     1     1     0
5 kmer with 3 clusters     2     0     0     2     0     0     2
5 kmer with 4 clusters     3     1     0     3     1     0     3

In [28]:
n_components = np.arange(2, 3)
models = [GMM(n, covariance_type='full', random_state=0).fit(kmer_table)
          for n in n_components]
print(m.bic(kmer_table) for m in models)


<generator object <genexpr> at 0x13036c750>


In [30]:
gmm.bic(kmer_table)

156283363.65769827

In [32]:
gmm6 = GMM(n_components=4).fit(kmer_table)
labels6 = gmm6.predict(kmer_table)
labels6

array([1, 0, 1, 1, 1, 2, 0, 0, 0, 1, 0, 1, 1, 0, 3, 3, 0, 0, 3, 3, 3, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 3, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 3, 1, 1, 1, 1, 1, 1, 3, 0, 0, 0, 0, 0, 0, 3, 3, 1, 1, 2, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 3, 3, 1, 0, 0, 0, 0, 0, 0, 3, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 1, 0, 1, 3, 3, 3, 3, 1, 0,
       0, 1, 1, 1, 3, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 3, 2, 0, 3, 1, 3, 1,
       1, 3, 3, 3, 3, 3, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 3, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 3, 3, 3, 1, 1, 1, 3, 3, 3, 3, 1,
       0, 1, 0, 1, 1, 1, 3, 1, 3, 3, 1, 0, 0, 0, 0, 0, 0, 3, 1, 1, 1, 3,
       1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 3, 1,
       0, 1, 3, 1, 3, 1, 0, 1, 3, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,