In [1]:
# import packages
import matplotlib
matplotlib.use('TkAgg')
import matplotlib.pyplot as plt
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import numpy as np

from pandas import Series, DataFrame
import Bio
from Bio import SeqIO,AlignIO
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.mixture import GaussianMixture as GMM


In [2]:
# methods

# parseFasta(data) credit to Luke
def parseFasta(data):
    d = {fasta.id : str(fasta.seq) for fasta in SeqIO.parse(data, "fasta")}
    pd.DataFrame([d])
    s = pd.Series(d, name='Sequence')
    s.index.name = 'ID'
    s.reset_index()
    return pd.DataFrame(s)

def get_kmer_table(paths,k_min,k_max):
    genes,gene_len = read_fasta(paths)
    count_vect = CountVectorizer(analyzer='char', ngram_range=(k_min, k_max))
    X = count_vect.fit_transform(genes)
    chars = count_vect.get_feature_names()
    kmers = X.toarray()
    kmer_freq = []
    for i in range(len(genes)):
        kmer_freq.append(kmers[i] / gene_len[i])
    input = pd.DataFrame(kmer_freq, columns=chars)
    return input

def get_gene_sequences(filename):
    genes = []
    for record in SeqIO.parse(filename, "fasta"):
        genes.append(str(record.seq))
    return genes

# genes: a list of gene sequences, which can directly be generated from get_gene_sequences().
def get_gene_len(genes):
    gene_len = []

    for i in range(len(genes)):
        gene_len.append(len(genes[i]))
    return gene_len

def read_fasta(paths):
    all_genes = []
    all_gene_len = []
    
    for path in paths:
        virus = parseFasta(path)
        virus = virus.drop_duplicates(keep="last")
        genes = list(virus['Sequence'])
        genes_seq = get_gene_sequences(path)
        gene_len = get_gene_len(genes_seq)
        all_genes = all_genes + genes_seq
        all_gene_len = all_gene_len + gene_len
    return all_genes,all_gene_len

def get_predictions(paths,k_min,k_max,num_class,cov_type):
    kmer_table = get_kmer_table(paths, k_min, k_max)
    gmm = GMM(n_components=num_class,covariance_type=cov_type).fit(kmer_table)
    labels = gmm.predict(kmer_table)
    return labels



In [ ]:
def cal_accuracy(labels, predictions):
    return 1-sum(abs(labels - predictions))/(len(labels))

def create_labels (files):
    labels = []
    for f in files:
        length = len(get_gene_sequences(f))
    
    return labels

In [ ]:
bat_len = len(get_gene_sequences("datasets/bat_flu.fa"))
penguin_len = len(get_gene_sequences("datasets/penguin_flu.fa"))
zeros = [0]*bat_len
labels1 = np.append(zeros, [1]*penguin_len, axis=None)

In [36]:
# change the following parameters to user inputs
paths = ["datasets/bat_flu.fa","datasets/penguin_flu.fa"]
k_min = 2
k_max = 3
num_class = 2
cov_type = 'full'
predictions1_1 = get_predictions(paths,k_min,k_max,num_class,cov_type)

In [37]:
predictions1_1

array([0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [38]:
labels1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [82]:
accuracy1_1 = 1 - sum(abs(labels1 - predictions1_1))/(bat_len+penguin_len)
accuracy1_1

0.8571428571428572

In [41]:
k_min = 4
k_max = 5
num_class = 2
cov_type = 'full'
predictions1_2 = get_predictions(paths,k_min,k_max,num_class,cov_type)

In [42]:
accuracy1_2 = 1 - sum(abs(labels1 - predictions1_2))/(bat_len+penguin_len)
accuracy1_2

0.49142857142857144

In [43]:
k_min = 2
k_max = 5
num_class = 2
cov_type = 'full'
predictions1_3 = get_predictions(paths,k_min,k_max,num_class,cov_type)

In [45]:
accuracy1_3 = 1 - sum(abs(labels1 - predictions1_3))/(bat_len+penguin_len)
accuracy1_3

0.6799999999999999

In [50]:
k_min = 2
k_max = 3
num_class = 2
cov_type = 'diag'
predictions1_4 = get_predictions(paths,k_min,k_max,num_class,cov_type)
accuracy1_4 = 1 - sum(abs(labels1 - predictions1_4))/(bat_len+penguin_len)
accuracy1_4

0.8457142857142858

In [51]:
k_min = 2
k_max = 3
num_class = 2
cov_type = 'tied'
predictions1_5 = get_predictions(paths,k_min,k_max,num_class,cov_type)
accuracy1_5 = 1 - sum(abs(labels1 - predictions1_5))/(bat_len+penguin_len)
accuracy1_5

0.6628571428571428

In [52]:
k_min = 2
k_max = 3
num_class = 2
cov_type = 'spherical'
predictions1_6 = get_predictions(paths,k_min,k_max,num_class,cov_type)
accuracy1_6 = 1 - sum(abs(labels1 - predictions1_6))/(bat_len+penguin_len)
accuracy1_6

0.8228571428571428

In [58]:
cat_len = len(get_gene_sequences("datasets/cat_flu.fa"))
labels2 = np.append(labels1, [2]*cat_len, axis=None)

In [53]:
paths = ["datasets/bat_flu.fa","datasets/penguin_flu.fa","datasets/cat_flu.fa"]
k_min = 2
k_max = 3
num_class = 3
cov_type = 'full'
predictions2_1 = get_predictions(paths,k_min,k_max,num_class,cov_type)

In [54]:
predictions2_1

array([0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0,
       2, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 2, 2, 2,
       2, 0, 2, 0, 1, 2, 2, 2, 2, 0, 2, 0, 1, 2, 2, 2, 2, 0, 2, 0, 1, 2,
       2, 2, 2, 0, 2, 0, 1, 2, 0, 1, 1, 0, 0, 0, 1, 1, 0, 2, 2, 2, 0, 2,
       0, 1, 2, 2, 2, 2, 1, 2, 2, 0, 0, 2, 2, 1, 0, 2, 0, 2, 2, 2, 0, 0,
       2, 2, 1, 2, 0, 1, 2, 0, 2, 2, 2, 2, 2, 2, 0, 2, 2, 0, 1, 2, 2, 2,
       0, 0, 1, 2, 2, 0, 0, 2, 2, 2, 2, 1, 2, 2, 2, 0, 2, 0, 2, 1, 2, 2,
       1, 0, 2, 0, 2, 2, 0, 0, 2, 0, 0, 0, 1, 2, 2, 2, 0, 0, 2, 2, 2, 0,
       2, 1, 1, 2, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 2, 2, 2,
       0, 2, 0, 1, 2, 0, 0, 2, 2, 2, 2, 2, 1, 2, 2, 2, 0, 2, 0, 1, 2, 2,
       2, 2, 0, 2, 0, 1, 2, 0, 0, 1, 0, 2, 2, 2, 2, 2, 0, 0, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 0, 2, 0, 1, 2, 0, 0, 0, 1, 1, 2, 0, 2, 0, 2, 2, 2,
       0, 0, 1])

In [66]:
def accuracy(labels,predictions):
    err = 0
    for i in range(len(labels)):
        if (labels[i] != predictions[i]):
            err += 1
    return (1-err/len(labels))

accuracy2_1 = accuracy(labels2,predictions2_1)
accuracy2_1

0.4290657439446367

In [68]:
k_min = 2
k_max = 5
num_class = 3
cov_type = 'full'
predictions2_3 = get_predictions(paths,k_min,k_max,num_class,cov_type)
accuracy2_3 = accuracy(labels2,predictions2_3)
accuracy2_3

0.24221453287197237

In [69]:
k_min = 2
k_max = 3
num_class = 3
cov_type = 'diag'
predictions2_4 = get_predictions(paths,k_min,k_max,num_class,cov_type)
accuracy2_4 = accuracy(labels2,predictions2_4)
accuracy2_4

0.3044982698961938

In [77]:
k_min = 2
k_max = 3
num_class = 3
cov_type = 'tied'
predictions2_5 = get_predictions(paths,k_min,k_max,num_class,cov_type)
accuracy2_5 = accuracy(labels2,predictions2_5)
accuracy2_5

0.4117647058823529

In [80]:
k_min = 2
k_max = 3
num_class = 3
cov_type = 'spherical'
predictions2_6 = get_predictions(paths,k_min,k_max,num_class,cov_type)
accuracy2_6 = accuracy(labels2,predictions2_6)
accuracy2_6

0.46366782006920415

In [86]:
paths = ["datasets/Dengue.fa","datasets/mers.fa"]
k_min = 2
k_max = 3
num_class = 2
cov_type = 'full'
predictions3_1 = get_predictions(paths,k_min,k_max,num_class,cov_type)

In [87]:
den_len = len(get_gene_sequences("datasets/Dengue.fa"))
mers_len = len(get_gene_sequences("datasets/mers.fa"))
zeros = np.zeros(den_len)
labels3 = np.append(zeros, [1]*mers_len,axis=None)

In [88]:
accuracy3_1 = 1-sum(abs(labels3 - predictions3_1))/(den_len+mers_len)
accuracy3_1

0.9725986148750376

In [91]:
k_min = 3
k_max = 3
num_class = 2
cov_type = 'full'
predictions3_2 = get_predictions(paths,k_min,k_max,num_class,cov_type)
accuracy3_2 = 1-sum(abs(labels3 - predictions3_2))/(den_len+mers_len)
accuracy3_2

0.020174646190906365

In [92]:
k_min = 4
k_max = 4
num_class = 2
cov_type = 'full'
predictions3_3 = get_predictions(paths,k_min,k_max,num_class,cov_type)
accuracy3_3 = 1-sum(abs(labels3 - predictions3_3))/(den_len+mers_len)
accuracy3_3

0.014152363745859708

In [93]:
k_min = 2
k_max = 3
num_class = 2
cov_type = 'diag'
predictions3_4 = get_predictions(paths,k_min,k_max,num_class,cov_type)
accuracy3_4 = 1-sum(abs(labels3 - predictions3_4))/(den_len+mers_len)
accuracy3_4

0.04727491719361643

In [96]:
k_min = 2
k_max = 3
num_class = 2
cov_type = 'tied'
predictions3_5 = get_predictions(paths,k_min,k_max,num_class,cov_type)
accuracy3_5 = 1-sum(abs(labels3 - predictions3_5))/(den_len+mers_len)
accuracy3_5

0.028906955736224038

In [97]:
k_min = 2
k_max = 3
num_class = 2
cov_type = 'spherical'
predictions3_6 = get_predictions(paths,k_min,k_max,num_class,cov_type)
accuracy3_6 = 1-sum(abs(labels3 - predictions3_6))/(den_len+mers_len)
accuracy3_6

0.9698885877747666

In [83]:
accu1 = [accuracy1_1,accuracy1_2,accuracy1_3,accuracy1_4,accuracy1_5,accuracy1_6]
accu1

[0.8571428571428572,
 0.49142857142857144,
 0.6799999999999999,
 0.8457142857142858,
 0.6628571428571428,
 0.8228571428571428]

In [84]:
accu2 = [accuracy2_1,accuracy2_2,accuracy2_3,accuracy2_4,accuracy2_5,accuracy2_6]
accu2

[0.4290657439446367,
 0.32179930795847755,
 0.24221453287197237,
 0.4982698961937716,
 0.4117647058823529,
 0.46366782006920415]

In [98]:
accu3 = [accuracy3_1,1-accuracy3_2,1-accuracy3_3,1-accuracy3_4,1-accuracy3_5,accuracy3_6]
accu3

[0.9725986148750376,
 0.9798253538090936,
 0.9858476362541403,
 0.9527250828063836,
 0.971093044263776,
 0.9698885877747666]

In [111]:
df = pd.DataFrame(data=[accu1,accu2,accu3], index=['Flu from bat or penguin (175 seqs)','Flu from bat or penguin or cat (289 seqs)','Dengue or Mers (3321 seqs)'])
df.rename(columns={0:'2-3mer with full covariance',
                   1:'4-5mer with full covariance',
                   2:'2-5mer with full covariance',
                   3:'2-3mer with diag covariance',
                   4: '2-3mer with tied covariance',
                   5:'2-3mer with spherical covariance'}, 
                 inplace=True)

In [112]:
df

2-3mer with full covariance  \
Flu from bat or penguin (175 seqs)                            0.857143   
Flu from bat or penguin or cat (289 seqs)                     0.429066   
Dengue or Mers (3321 seqs)                                    0.972599   

                                           4-5mer with full covariance  \
Flu from bat or penguin (175 seqs)                            0.491429   
Flu from bat or penguin or cat (289 seqs)                     0.321799   
Dengue or Mers (3321 seqs)                                    0.979825   

                                           2-5mer with full covariance  \
Flu from bat or penguin (175 seqs)                            0.680000   
Flu from bat or penguin or cat (289 seqs)                     0.242215   
Dengue or Mers (3321 seqs)                                    0.985848   

                                           2-3mer with diag covariance  \
Flu from bat or penguin (175 seqs)                            0.845714   
Flu from bat or penguin or cat (289 seqs)                     0.498270   
Dengue or Mers (3321 seqs)                                    0.952725   

                                           2-3mer with tied covariance  \
Flu from bat or penguin (175 seqs)                            0.662857   
Flu from bat or penguin or cat (289 seqs)                     0.411765   
Dengue or Mers (3321 seqs)                                    0.971093   

                                           2-3mer with spherical covariance  
Flu from bat or penguin (175 seqs)                                 0.822857  
Flu from bat or penguin or cat (289 seqs)                          0.463668  
Dengue or Mers (3321 seqs)                                         0.969889

In [107]:
len(labels3)

3321

In [108]:
len(labels2)

289

In [110]:
len(labels1)

175